coverage:
    precision: 2
    round: down
    range: "70...100"
    status:
        project:
            default:
                target: 70%
                threshold: 1%
        patch:
            default:
                target: 70%
                threshold: 1%
ignore:
    - "core/ui"
    - "app/src/main/java/com/toquete/boxbox/util"
    - "core/ui/src/main/java/com/toquete/boxbox/core/ui/theme"
    - "**/*Activity*"
    - "**/*Module*"
    - "**/*Application*"
    - "**/*Composable*"
    - "**/*Preview*"
    - "**/*Stable*"
    - "**/*Generated*"
    - "**/*Destination*"
    - "**/*Navigation*"
    - "**/*Hilt*"
    - "**/*Factory*"
    - "**/*Injector*"
    - "**/*Module*"
    - "**/*FirebaseDatabase*"
    - "**/*MainActivity*"