coverage:
    precision: 2
    round: down
    range: "70...100"
    status:
        project:
            default:
                target: 70%
                threshold: 1%
        patch:
            default:
                target: 70%
                threshold: 1%
ignore:
    - "core/database"
    - "core/ui"
    - "app/src/main/java/com/toquete/boxbox/util"
    - "**/*Activity*"
    - "**/*Module*"
    - "**/*Application*"
    - "**/*Worker*"
    - "**/*Composable*"