naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['@Composable', '@Test']
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
  active: true
  LongParameterList:
    active: true
    ignoreDefaultParameters: true

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: ['@Preview']
