naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']

complexity:
  active: true
  LongParameterList:
    active: true
    ignoreDefaultParameters: true
  LongMethod:
    active: true
    threshold: 120

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: ['Preview']
  UnnecessaryAbstractClass:
    active: true
    ignoreAnnotated: ['Module']
  WildcardImport:
    active: true
    excludeImports: ['io.ktor.*']

formatting:
  NoWildcardImports:
    active: false
